### ISSUE TITLE
Implement PostHog analytics tracking

### ISSUE THREAD

**Issue by shige** [giselles-ai/giselle#123]
## Task description
Implement PostHog for analytics tracking and user behavior insights in our application.

## Background
The integration of PostHog is necessary for enhancing our data analytics capabilities. This task is crucial as it will allow us to better understand user engagement and optimize our product based on real usage data. The terms of service have been updated (see [Terms of Service](https://giselles.ai/legal/terms)) with an effective date of December 02, 2024, allowing us to release this to the production environment after that date.

## TODO (Optional)
- [x] Update [Giselle Terms of Service](https://giselles.ai/legal/terms).
- [x] Implement.

**Comment by shige** [comment]
> * [x]  Update [Giselle Terms of Service](https://giselles.ai/legal/terms).

@koji-m 

We have updated the terms of service and released them today.  
Please proceed with the release on or after December 2nd!

- ref: https://github.com/giselles-ai/giselle/pull/112

**Comment by koji-m** [comment]
Change of https://github.com/giselles-ai/giselle/pull/112 contained error. 
Environment variable name needs to be fixed. ref: https://github.com/giselles-ai/giselle/blob/main/app/posthog-page-view.tsx#L8 
`NEXT_PUBLIC_ENABLE_ANALYTICS` -> `NEXT_PUBLIC_ENABLE_POSTHOG`

**Comment by koji-m** [comment]
Fixed https://github.com/giselles-ai/giselle/pull/156 and all tasks done.
