### ISSUE TITLE
Sources of Text Generator Prompt not displayed

### ISSUE THREAD

**Issue by koji-m** [giselles-ai/giselle#137]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](../discussions/categories/q-a).
- [X] I have searched for existing issues [search for existing issues](../issues), including closed ones.

### Cloud or Self Hosted

Cloud

### Steps to reproduce

1. Create `Text Generator` node and push value (generate text).
2. Add another `Text Generator` node.
3. Select the 2nd `Text Generator's` Prompt node and click Source (+ ) button.

### Expected Behavior

List up 1st `Text Generator` node's output.

### Actual Behavior

Nothing displayed.

### Additional Context

Also `Web Search` node don't output result.

**Comment by koji-m** [comment]
error logs

```
TypeError: Cannot read properties of undefined (reading 'id')
    at sI (/var/task/.next/server/app/(playground)/p/[agentId]/page.js:8:8722)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async onFinish (/var/task/.next/server/app/(playground)/p/[agentId]/page.js:82:374)
    at async Object.flush (/var/task/.next/server/app/(playground)/p/[agentId]/page.js:7:58335)
```

**Comment by koji-m** [comment]
https://github.com/giselles-ai/giselle/pull/138

**Comment by satococoa** [comment]
fixed https://github.com/giselles-ai/giselle/pull/139
