### ISSUE TITLE
Change indentation from tabs to spaces

### ISSUE THREAD

**Issue by shige** [giselles-ai/giselle#214]
## Task description
Change indentation from tabs to spaces throughout the codebase.

## Background
The current use of tab indentation makes code reviews on GitHub pull requests difficult to read. Initially, the choice of tabs or spaces seemed inconsequential, but as the code has grown with deeper nesting, the productivity of code review sessions has declined.

## TODO
- [ ] Replace tab characters with spaces (using biome).
- [ ] Verify that the codebase maintains its original functionality after changes.

## Additional notes

**Comment by toyamarinyon** [comment]
@shige I set the number of spaces per tab in GitHub's tab size preference to two. 

https://github.com/settings/appearance

![image](https://github.com/user-attachments/assets/8655aab8-963d-468a-b470-5e875c4815a4)


Can this setting solve the problem?

**Comment by shige** [comment]
@toyamarinyon 
Are you assuming that everyone will configure it themselves?  
I think people visiting this repository might simply find it hard to read, so is there any issue with changing the indent to spaces?  

In my opinion, many JavaScript and TypeScript projects adopt a 2-space indent.  
On the other hand, could you explain the reasoning for continuing to use tabs?

**Comment by toyamarinyon** [comment]
@shige I follow the philosophy of Biome's formatter option.

> Having such a strong opinion on formatting may seem heavy-handed, but the benefits quickly become clear after adoption. All of the discussions about where spaces should go, whether a line should be broken out, whether a line should be indented, and so many more simply vanish. Trivial, bike-shedding discussions no longer distract from focusing on what matters. Code reviews become free of re-formatting requests and cyclical debates. All it takes is trust that Biome does its best to format code cleanly, legibly, and consistently.
> https://biomejs.dev/formatter/option-philosophy

The pros and cons of having Tab as the default are also discussed in Prettier, which Biome refers to, and there are various opinions.

https://github.com/prettier/prettier/issues/7475

I'm in the position of wanting it to be the default until I need it, rather than having a strong preference for Tab, so I'm happy to change it to Space if I need to.

cf: https://sosukesuzuki.dev/posts/prettier-uses-tabs/ (Japanese contents by Prettier's maintainer)

**Comment by shige** [comment]
I don't want to prolong the discussion, so I'll temporarily address the issue by changing my GitHub settings. However, I'll keep the issue open.

**Comment by shige** [comment]
- [Default to tabs instead of spaces for an ‘accessible first’ environment · Alexander Sandberg](https://alexandersandberg.com/articles/default-to-tabs-instead-of-spaces-for-an-accessible-first-environment/)

I understand that using tabs is better from an accessibility perspective, so I'll close this issue. If needed, I'll reopen it or create a new issue in the future!
