### ISSUE TITLE
Enable controlling log level

### ISSUE THREAD

**Issue by Rindrics** [giselles-ai/giselle#87]
## Task description

Implement a leveled logging system that enables structured output for debugging

## Background

We need to strike a balance between two competing needs:
- Including detailed debug information for development and troubleshooting
- Maintaining clean and focused console output for production use

Key considerations:
- Development environments need verbose logging for debugging
- Production environments should show only essential information

## Additional notes

- It would be better if the logger tool have structured-logging function

**Comment by rindrics** [comment]
we also need the reduct (mask) function for logger tool

discussed here: https://github.com/giselles-ai/giselle/pull/88#issuecomment-2469752968
